# Generated by Django 3.1.4 on 2021-01-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stormwind_app', '0003_deal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
    ]
