# Generated by Django 3.1.4 on 2021-02-02 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stormwind_app', '0004_auto_20210115_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил'),
        ),
    ]
