# Generated by Django 3.1.4 on 2021-02-02 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stormwind_app', '0005_property_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stormwind_app.client', verbose_name='Клиент'),
        ),
    ]
