# Generated by Django 3.1.4 on 2021-02-05 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stormwind_app', '0009_deal_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stormwind_app.offer', verbose_name='Номер предложения'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='req',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stormwind_app.req', verbose_name='Номер запроса'),
        ),
    ]
