# Generated by Django 3.1.4 on 2021-02-05 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stormwind_app', '0010_auto_20210205_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор сделки'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stormwind_app.offer', verbose_name='Номер предложения'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='req',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stormwind_app.req', verbose_name='Номер запроса'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stormwind_app.client', verbose_name='Номер клиента'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Дом', 'Дом'), ('Квартира', 'Квартира'), ('Земля', 'Земля')], max_length=20, null=True, verbose_name='Тип собственности'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='middle_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='req',
            name='property_type',
            field=models.CharField(choices=[('Дом', 'Дом'), ('Квартира', 'Квартира'), ('Земля', 'Земля')], default=12, max_length=100, verbose_name='Тип имущества'),
            preserve_default=False,
        ),
    ]
